apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: andysong-shop-tls
spec:
  secretName: andysong-shop
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: andysong.shop
  dnsNames:
    - andysong.shop
    - www.andysong.shop
